/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PanchakarmaRouteImport } from './routes/panchakarma'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as DiseasesIndexRouteImport } from './routes/diseases/index'
import { Route as DiseasesSlugRouteImport } from './routes/diseases/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchakarmaRoute = PanchakarmaRouteImport.update({
  id: '/panchakarma',
  path: '/panchakarma',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesIndexRoute = DiseasesIndexRouteImport.update({
  id: '/diseases/',
  path: '/diseases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesSlugRoute = DiseasesSlugRouteImport.update({
  id: '/diseases/$slug',
  path: '/diseases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/panchakarma': typeof PanchakarmaRoute
  '/treatments': typeof TreatmentsRoute
  '/wellness': typeof WellnessRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/diseases/': typeof DiseasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/panchakarma': typeof PanchakarmaRoute
  '/treatments': typeof TreatmentsRoute
  '/wellness': typeof WellnessRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/diseases': typeof DiseasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/panchakarma': typeof PanchakarmaRoute
  '/treatments': typeof TreatmentsRoute
  '/wellness': typeof WellnessRoute
  '/diseases/$slug': typeof DiseasesSlugRoute
  '/diseases/': typeof DiseasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/blog'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/doctors'
    | '/gallery'
    | '/panchakarma'
    | '/treatments'
    | '/wellness'
    | '/diseases/$slug'
    | '/diseases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/blog'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/doctors'
    | '/gallery'
    | '/panchakarma'
    | '/treatments'
    | '/wellness'
    | '/diseases/$slug'
    | '/diseases'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/blog'
    | '/book'
    | '/contact'
    | '/dashboard'
    | '/doctor'
    | '/doctors'
    | '/gallery'
    | '/panchakarma'
    | '/treatments'
    | '/wellness'
    | '/diseases/$slug'
    | '/diseases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DoctorRoute: typeof DoctorRoute
  DoctorsRoute: typeof DoctorsRoute
  GalleryRoute: typeof GalleryRoute
  PanchakarmaRoute: typeof PanchakarmaRoute
  TreatmentsRoute: typeof TreatmentsRoute
  WellnessRoute: typeof WellnessRoute
  DiseasesSlugRoute: typeof DiseasesSlugRoute
  DiseasesIndexRoute: typeof DiseasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchakarma': {
      id: '/panchakarma'
      path: '/panchakarma'
      fullPath: '/panchakarma'
      preLoaderRoute: typeof PanchakarmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/': {
      id: '/diseases/'
      path: '/diseases'
      fullPath: '/diseases/'
      preLoaderRoute: typeof DiseasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases/$slug': {
      id: '/diseases/$slug'
      path: '/diseases/$slug'
      fullPath: '/diseases/$slug'
      preLoaderRoute: typeof DiseasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DoctorRoute: DoctorRoute,
  DoctorsRoute: DoctorsRoute,
  GalleryRoute: GalleryRoute,
  PanchakarmaRoute: PanchakarmaRoute,
  TreatmentsRoute: TreatmentsRoute,
  WellnessRoute: WellnessRoute,
  DiseasesSlugRoute: DiseasesSlugRoute,
  DiseasesIndexRoute: DiseasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
